import type { Metadata } from 'next'
import { Inter, Silkscreen } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const silkscreen = Silkscreen({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-bg-color text-white'>
      <body className={silkscreen.className}>{children}</body>
    </html>
  )
}
